### PR TITLE
Communication Preferences #51

### LINKED ISSUE #51: Communication Preferences
- I should be able to set communication preferences on Contact object. If the contact wants to receive emails, email field of the contact should be required. If the contact wants to receive calls/sms, phone field should be required. 

- If one of the preferences is changed, email/phone fields should be validated again

### PR DESCRIPTION
**Pull request by t-gul**
- “Email” checkbox field is created under “Contact” object
- “Phone” checkbox field is created under “Contact” object
- “Communication Preference” validation rule is created under “Contact” object.
- “Communication Preferences” section is created at related Page Layouts under “Contact” object.
- “Email”, “Phone” standard fields and “Email”, “Phone” custom checkbox fields are putted in “Communication Preferences” section.
- Package.xml and Admin Profile is updated.

Test Cases Document:
[Test Cases#51.pdf](https://github.com/sgoEma/EventManagement/files/8563737/Test.Cases.51.pdf)

Org Credentials:
Username: [test-ck9gyzzwcxtj@example.com](mailto:test-ck9gyzzwcxtj@example.com)
Password: -5evGoevfsorh

### CODE REVIEW

**Review by bmtemakina — COMMENTED** [review]
Maybe we can make fields' API names more specific, something like "Email_Checkbox __c" because there already are standard fields named "Email" and "Phone" and this can cause confusion.

**Comment by t-gul** [comment]
> Maybe we can make fields' API names more specific, something like "Email_Checkbox __c" because there already are standard fields named "Email" and "Phone" and this can cause confusion.

Thanks for comment @bmtemakina. 

Yes It can be confused somewhere like Queries. It can be changed like Email Opt In and Phone Opt In. If you approve changing.

**Comment by bmtemakina** [comment]
> > Maybe we can make fields' API names more specific, something like "Email_Checkbox __c" because there already are standard fields named "Email" and "Phone" and this can cause confusion.
> 
> Thanks for comment @bmtemakina.
> 
> Yes It can be confused somewhere like Queries. It can be changed like Email Opt In and Phone Opt In. If you approve changing.

Sounds good :)

**Comment by t-gul** [comment]
> > > Maybe we can make fields' API names more specific, something like "Email_Checkbox __c" because there already are standard fields named "Email" and "Phone" and this can cause confusion.
> > 
> > 
> > Thanks for comment @bmtemakina.
> > Yes It can be confused somewhere like Queries. It can be changed like Email Opt In and Phone Opt In. If you approve changing.
> 
> Sounds good :)

@bmtemakina "Email__c", "Phone__c" field names are changed into "Email_Opt_In__c", " Phone_Opt_In__c".

**Review by bmtemakina — APPROVED** [review]

**Review by secoEmakina — APPROVED** [review]

**Pull request merged**
